"""Type stubs for dagron._internal (Rust extension module)."""

from collections.abc import Callable, Iterator, Sequence
from typing import Any, Literal

from dagron.builder import DAGBuilder

class NodeId:
    """Snapshot identifier for a node, returned by enumeration methods.

    Carries the node's `name` plus a snapshot internal `index`. The `index`
    may be reused after node removal — for a stable handle, use `NodeRef`.
    """

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class NodeRef:
    """A stable, persistent handle to a node.

    Returned by `DAG.add_node`. Survives unrelated mutations and is invalidated
    only when its own node is removed (or removed-and-readded with the same
    name, which yields a fresh handle with a different `epoch`). Pass it
    anywhere a `str` name is accepted.
    """

    @property
    def name(self) -> str: ...
    @property
    def epoch(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

# Public alias: anywhere dagron accepts a node identifier, you can pass either
# a string name or a NodeRef.
type NodeArg = str | NodeRef

class ScheduledNode:
    """A node with scheduling information."""

    @property
    def node(self) -> NodeId: ...
    @property
    def start_time(self) -> float: ...
    @property
    def duration(self) -> float: ...
    def __repr__(self) -> str: ...

class ExecutionStep:
    """A step in an execution plan containing nodes to run in parallel."""

    @property
    def step_index(self) -> int: ...
    @property
    def nodes(self) -> list[ScheduledNode]: ...
    def __repr__(self) -> str: ...

class ExecutionPlan:
    """An execution plan for the DAG."""

    @property
    def steps(self) -> list[ExecutionStep]: ...
    @property
    def total_nodes(self) -> int: ...
    @property
    def max_parallelism(self) -> int: ...
    @property
    def estimated_makespan(self) -> float: ...
    @property
    def critical_path(self) -> list[NodeId] | None: ...
    def __repr__(self) -> str: ...

class ReachabilityIndex:
    """Precomputed reachability index for O(1) ancestor/descendant queries.

    Build once with ``DAG.build_reachability_index()``, then query with
    ``can_reach()``, ``reachable_from()``, and ``ancestors_of()``.

    Note: The index becomes stale if the DAG is mutated after building.
    """

    def can_reach(self, from_node: NodeArg, to_node: NodeArg) -> bool: ...
    def reachable_from(self, node: NodeArg) -> list[str]: ...
    def ancestors_of(self, node: NodeArg) -> list[str]: ...
    def node_count(self) -> int: ...

class GraphStats:
    """Comprehensive graph statistics."""

    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def density(self) -> float: ...
    @property
    def longest_path_length(self) -> int: ...
    @property
    def avg_in_degree(self) -> float: ...
    @property
    def avg_out_degree(self) -> float: ...
    @property
    def max_in_degree(self) -> int: ...
    @property
    def max_out_degree(self) -> int: ...
    @property
    def root_count(self) -> int: ...
    @property
    def leaf_count(self) -> int: ...
    @property
    def is_weakly_connected(self) -> bool: ...
    @property
    def component_count(self) -> int: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class GraphDiff:
    """Result of diffing two DAGs."""

    @property
    def added_nodes(self) -> list[str]: ...
    @property
    def removed_nodes(self) -> list[str]: ...
    @property
    def changed_nodes(self) -> list[str]: ...
    @property
    def added_edges(self) -> list[tuple[str, str]]: ...
    @property
    def removed_edges(self) -> list[tuple[str, str]]: ...
    @property
    def changed_edges(self) -> list[tuple[str, str]]: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class NodeIterator:
    """Lazy iterator over nodes."""

    def __iter__(self) -> NodeIterator: ...
    def __next__(self) -> NodeId: ...
    def __len__(self) -> int: ...
    def collect(self) -> list[NodeId]: ...
    def __repr__(self) -> str: ...

class NodeLevelIterator:
    """Lazy iterator over topological levels."""

    def __iter__(self) -> NodeLevelIterator: ...
    def __next__(self) -> list[NodeId]: ...
    def __len__(self) -> int: ...
    def collect(self) -> list[list[NodeId]]: ...
    def __repr__(self) -> str: ...

class DAG:
    """A directed acyclic graph backed by Rust."""

    def __init__(self) -> None: ...

    # --- Properties ---
    @property
    def generation(self) -> int: ...

    # --- Construction ---
    def add_node(
        self,
        name: str,
        payload: Any = None,
        metadata: Any = None,
    ) -> NodeRef: ...
    def add_nodes(
        self,
        nodes: Sequence[str | tuple[str, Any] | tuple[str, Any, Any]],
    ) -> list[NodeRef]: ...
    def node_ref(self, name: str) -> NodeRef | None: ...
    def add_edge(
        self,
        from_node: NodeArg,
        to_node: NodeArg,
        weight: float | None = None,
        label: str | None = None,
    ) -> None: ...
    def add_edges(
        self,
        edges: list[
            tuple[NodeArg, NodeArg]
            | tuple[NodeArg, NodeArg, float]
            | tuple[NodeArg, NodeArg, float, str]
        ],
    ) -> None: ...
    def remove_node(self, node: NodeArg) -> None: ...
    def remove_edge(self, from_node: NodeArg, to_node: NodeArg) -> None: ...
    @staticmethod
    def builder() -> DAGBuilder: ...

    # --- Introspection ---
    def has_node(self, node: NodeArg) -> bool: ...
    def has_edge(self, from_node: NodeArg, to_node: NodeArg) -> bool: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def get_payload(self, node: NodeArg) -> Any: ...
    def set_payload(self, node: NodeArg, payload: Any) -> None: ...
    def get_metadata(self, node: NodeArg) -> Any: ...
    def set_metadata(self, node: NodeArg, metadata: Any) -> None: ...
    def predecessors(self, node: NodeArg) -> list[NodeId]: ...
    def successors(self, node: NodeArg) -> list[NodeId]: ...
    def ancestors(self, node: NodeArg) -> list[NodeId]: ...
    def descendants(self, node: NodeArg) -> list[NodeId]: ...
    def in_degree(self, node: NodeArg) -> int: ...
    def out_degree(self, node: NodeArg) -> int: ...
    def roots(self) -> list[NodeId]: ...
    def leaves(self) -> list[NodeId]: ...
    def nodes(self) -> list[NodeId]: ...
    def node_names(self) -> list[str]: ...
    def edges(self) -> list[tuple[str, str]]: ...
    def iter_nodes(self) -> NodeIterator: ...
    def iter_roots(self) -> NodeIterator: ...
    def iter_leaves(self) -> NodeIterator: ...
    def iter_ancestors(self, node: NodeArg) -> NodeIterator: ...
    def iter_descendants(self, node: NodeArg) -> NodeIterator: ...

    # --- Validation ---
    def validate(self) -> bool: ...

    # --- Topological sorting ---
    def topological_sort(self) -> list[NodeId]: ...
    def topological_sort_dfs(self) -> list[NodeId]: ...
    def topological_levels(self) -> list[list[NodeId]]: ...
    def all_topological_orderings(self, limit: int | None = None) -> list[list[NodeId]]: ...
    def iter_topological_sort(self) -> NodeIterator: ...
    def iter_topological_levels(self) -> NodeLevelIterator: ...

    # --- Priority sorting ---
    def topological_sort_priority(
        self, priorities: dict[str, float] | None = None
    ) -> list[NodeId]: ...
    def topological_levels_priority(
        self, priorities: dict[str, float] | None = None
    ) -> list[list[NodeId]]: ...

    # --- Scheduling ---
    def execution_plan(self, costs: dict[str, float] | None = None) -> ExecutionPlan: ...
    def execution_plan_constrained(
        self,
        max_workers: int,
        costs: dict[str, float] | None = None,
    ) -> ExecutionPlan: ...
    def critical_path(
        self, costs: dict[str, float] | None = None
    ) -> tuple[list[NodeId], float]: ...

    # --- Serialization ---
    def to_json(self, payload_serializer: Callable[[Any], Any] | None = None) -> str: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...
    def to_dot(
        self,
        node_attrs: Callable[[str, Any], str | None] | None = None,
    ) -> str: ...
    def to_mermaid(self) -> str: ...
    def to_bytes(self, payload_serializer: Callable[[Any], Any] | None = None) -> bytes: ...
    @classmethod
    def from_bytes(
        cls,
        data: bytes,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

    # --- Transforms ---
    def reverse(self) -> DAG: ...
    def collapse(
        self,
        nodes: Sequence[NodeArg],
        collapsed_name: str,
        payload: Any = None,
    ) -> DAG: ...
    def dominator_tree(self, root: NodeArg) -> list[tuple[str, str]]: ...
    def snapshot(self) -> DAG: ...
    def transitive_reduction(self) -> DAG: ...
    def transitive_closure(self) -> DAG: ...
    def filter(self, predicate: Callable[[str, Any], bool]) -> DAG: ...
    def merge(
        self,
        other: DAG,
        conflict: Literal["keep_first", "keep_second", "error"] = "keep_first",
        conflict_resolver: Callable[[str, Any, Any], Any] | None = None,
    ) -> DAG: ...

    # --- Incremental ---
    def dirty_set(self, changed: Sequence[NodeArg]) -> list[str]: ...
    def change_provenance(self, changed: Sequence[NodeArg]) -> dict[str, list[str]]: ...

    # --- Subgraph ---
    def subgraph(self, nodes: Sequence[NodeArg]) -> DAG: ...
    def subgraph_by_depth(
        self,
        root: NodeArg,
        depth: int,
        direction: Literal["forward", "backward", "both"] = "both",
    ) -> DAG: ...

    # --- Paths ---
    def all_paths(
        self,
        from_node: NodeArg,
        to_node: NodeArg,
        limit: int | None = None,
    ) -> list[list[NodeId]]: ...
    def shortest_path(self, from_node: NodeArg, to_node: NodeArg) -> list[NodeId] | None: ...
    def longest_path(
        self,
        from_node: NodeArg,
        to_node: NodeArg,
        costs: dict[str, float] | None = None,
    ) -> tuple[list[NodeId], float] | None: ...

    # --- Reachability ---
    def build_reachability_index(self) -> ReachabilityIndex: ...
    def is_ancestor(self, ancestor: NodeArg, descendant: NodeArg) -> bool: ...

    # --- Matching ---
    def nodes_matching_regex(self, pattern: str) -> list[NodeId]: ...
    def nodes_matching_glob(self, pattern: str) -> list[NodeId]: ...

    # --- Statistics ---
    def stats(self) -> GraphStats: ...

    # --- Diff ---
    def diff(self, other: DAG) -> GraphDiff: ...

    # --- Serialization (file) ---
    def save(
        self,
        path: str,
        payload_serializer: Callable[[Any], Any] | None = None,
    ) -> None: ...
    @classmethod
    def load(
        cls,
        path: str,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

    # --- Cache ---
    def cache_info(self) -> dict[str, int]: ...
    def clear_cache(self) -> None: ...

    # --- Protocols ---
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    # --- Display (monkey-patched) ---
    def pretty_print(
        self,
        *,
        layout: Literal["vertical", "horizontal"] = "vertical",
        max_nodes: int = 50,
        show_payloads: bool = False,
        node_formatter: Callable[[str, Any], str] | None = None,
    ) -> str: ...
    def _repr_svg_(self) -> str: ...

    # --- Integration (monkey-patched) ---
    @staticmethod
    def from_records(
        records: Any,
        *,
        name_field: str = "name",
        edge_fn: Callable[[Any], list[str]] | None = None,
        payload_fn: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

    # --- Analysis (monkey-patched) ---
    def explain(
        self,
        node: NodeArg,
        costs: dict[str, float] | None = None,
    ) -> Any: ...
    def what_if(
        self,
        *,
        remove_nodes: Sequence[NodeArg] | None = None,
        remove_edges: Sequence[tuple[NodeArg, NodeArg]] | None = None,
        add_nodes: Sequence[str] | None = None,
        add_edges: Sequence[tuple[NodeArg, NodeArg]] | None = None,
        costs: dict[str, float] | None = None,
    ) -> Any: ...
    def lint(
        self,
        *,
        max_fan_in: int = 10,
        max_fan_out: int = 10,
        max_depth: int = 50,
        warn_disconnected: bool = True,
        warn_redundant_edges: bool = True,
    ) -> Any: ...
    def query(self, expr: str) -> list[str]: ...

# Dashboard (requires --features dashboard)
class RustDashboardServer:
    def __init__(self, host: str, port: int) -> None: ...
    @property
    def port(self) -> int: ...
    def stop(self) -> None: ...
    def reset(self, dag_dot: str, node_names: list[str], edges: list[tuple[str, str]]) -> None: ...
    def node_started(self, name: str) -> None: ...
    def node_finished(self, name: str, status: str, error: str | None = None) -> None: ...
    def execution_finished(
        self,
        total_duration: float,
        succeeded: int,
        failed: int,
        skipped: int = 0,
        timed_out: int = 0,
        cancelled: int = 0,
    ) -> None: ...
    def set_gate_callback(self, approve_fn: Any, reject_fn: Any, has_gate_fn: Any) -> None: ...
    def set_waiting_gates(self, gates: list[str]) -> None: ...

# Exceptions
class DagronError(Exception): ...
class CycleError(DagronError): ...
class NodeNotFoundError(DagronError): ...
class DuplicateNodeError(DagronError): ...
class EdgeNotFoundError(DagronError): ...
class GraphError(DagronError): ...
class StaleNodeRefError(DagronError): ...
