"""Generate `.pyi` type stubs that statically type a built DAG's results.

After building a DAG, call `generate_stub(dag, type_hints={...})` to emit
a stub describing each node's return type. Saving the result alongside
your code lets `mypy` give precise types to `result["my_node"]` lookups.

Example::

    from dagron import DAG, flow, task
    from dagron.stubgen import generate_stub

    @task
    def fetch() -> list[int]: ...

    @task
    def total(rows: list[int]) -> int: ...

    @flow
    def pipeline():
        return total(fetch())

    dag = pipeline.dag()
    print(generate_stub(dag, name="MyResult"))

emits::

    from typing import overload, Literal
    from dagron.execution import NodeResult

    class MyResult:
        @overload
        def __getitem__(self, key: Literal["fetch"]) -> NodeResult[list[int]]: ...
        @overload
        def __getitem__(self, key: Literal["total"]) -> NodeResult[int]: ...
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, get_args, get_origin, get_type_hints

from dagron.flow import _get_spec

if TYPE_CHECKING:
    from collections.abc import Callable

    from dagron._internal import DAG


def _format_type(t: Any) -> str:
    """Format a type annotation for inclusion in a .pyi file.

    Handles generic aliases (`list[int]`, `dict[str, int]`, `int | None`)
    by recursively formatting the parameters.
    """
    if t is type(None):
        return "None"

    # Generic alias: list[int], dict[str, int], Union, etc.
    origin = get_origin(t)
    args = get_args(t)
    if origin is not None and args:
        import types
        import typing

        # Special-case PEP 604 unions ("int | None") and typing.Union
        if origin is typing.Union or origin is types.UnionType:
            return " | ".join(_format_type(a) for a in args)

        origin_str = _format_type(origin)
        args_str = ", ".join(_format_type(a) for a in args)
        return f"{origin_str}[{args_str}]"

    if hasattr(t, "__module__") and hasattr(t, "__qualname__"):
        qualname: str = t.__qualname__
        if t.__module__ == "builtins":
            return qualname
        return f"{t.__module__}.{qualname}"
    return repr(t)


def _infer_type(fn: Callable[..., Any]) -> str | None:
    """Extract a function's return type as a stringified annotation, or None."""
    try:
        hints = get_type_hints(fn)
    except (NameError, AttributeError):
        return None
    rt = hints.get("return")
    if rt is None:
        return None
    return _format_type(rt)


def generate_stub(
    dag: DAG,
    *,
    type_hints: dict[str, type | str] | None = None,
    tasks: dict[str, Callable[..., Any]] | None = None,
    name: str = "TypedExecutionResult",
) -> str:
    """Generate a `.pyi` stub for typed lookup of DAG results.

    Args:
        dag: The built DAG to introspect.
        type_hints: Optional explicit mapping of node-name to result type
            (or stringified annotation). Wins over inferred hints.
        tasks: Optional mapping of node-name to the implementing function.
            Used to infer return types when no explicit hint is provided.
            If a node-name has a corresponding `@dagron.task`-decorated
            function in scope, its annotation is picked up automatically.
        name: Class name for the generated typed result wrapper.

    Returns:
        A `.pyi` source string.
    """
    type_hints = dict(type_hints or {})
    tasks = tasks or {}

    # Discover types from each node's task function (if any).
    annotations: dict[str, str] = {}
    for node in dag.nodes():
        n = node.name
        if n in type_hints:
            ann = type_hints[n]
            annotations[n] = ann if isinstance(ann, str) else _format_type(ann)
            continue
        fn = tasks.get(n)
        if fn is not None:
            inferred = _infer_type(fn)
            if inferred is not None:
                annotations[n] = inferred
                continue
            # Fall back to the TaskSpec's wrapped function
            try:
                spec = _get_spec(fn)
                inferred2 = _infer_type(spec.fn)
                if inferred2 is not None:
                    annotations[n] = inferred2
                    continue
            except TypeError:
                pass
        annotations[n] = "Any"

    lines: list[str] = [
        '"""Generated by dagron.stubgen — do not edit by hand."""',
        "",
        "from typing import Any, Literal, overload",
        "",
        "from dagron.execution import NodeResult",
        "",
        "",
        f"class {name}:",
    ]

    for node_name, ret in sorted(annotations.items()):
        lines.append("    @overload")
        lines.append(
            f"    def __getitem__(self, key: Literal[{node_name!r}]) -> NodeResult[{ret}]: ..."
        )

    # Default fallback overload
    lines.append("    @overload")
    lines.append("    def __getitem__(self, key: str) -> NodeResult[Any]: ...")

    if not annotations:
        # Empty class needs a body
        lines.append("    pass")

    lines.append("")
    return "\n".join(lines)
