"""dagron — A fast Rust-backed DAG engine for Python."""

from dagron._internal import (
    DAG,
    CycleError,
    DagronError,
    DuplicateNodeError,
    EdgeNotFoundError,
    ExecutionPlan,
    ExecutionStep,
    GraphDiff,
    GraphError,
    GraphStats,
    NodeId,
    NodeIterator,
    NodeLevelIterator,
    NodeNotFoundError,
    ReachabilityIndex,
    ScheduledNode,
)
from dagron._patches import apply_patches as _apply_patches
from dagron.analysis import (
    DAGSchema,
    LintReport,
    LintSeverity,
    LintWarning,
    NodeExplanation,
    WhatIfResult,
)
from dagron.builder import DAGBuilder
from dagron.compose import compose
from dagron.dataframe import (
    ColumnSchema,
    DataFramePipeline,
    DataFrameSchema,
    SchemaViolation,
    validate_schema,
)
from dagron.display import pretty_print
from dagron.execution import (
    AsyncDAGExecutor,
    CheckpointExecutor,
    CheckpointInfo,
    ConditionalDAGBuilder,
    ConditionalExecutor,
    DAGExecutor,
    ExecutionCallbacks,
    ExecutionResult,
    ExecutionTrace,
    IncrementalExecutor,
    IncrementalResult,
    NodeProfile,
    NodeResult,
    NodeStatus,
    Pipeline,
    ProfileReport,
    ReactiveDAG,
    TraceEvent,
    TraceEventType,
    profile_execution,
    task,
)
from dagron.integration import from_records
from dagron.versioning import Mutation, MutationType, VersionedDAG

_apply_patches()
del _apply_patches

__version__ = "0.1.0"

__all__ = [
    "DAG",
    "AsyncDAGExecutor",
    "CheckpointExecutor",
    "CheckpointInfo",
    "ColumnSchema",
    "ConditionalDAGBuilder",
    "ConditionalExecutor",
    "CycleError",
    "DAGBuilder",
    "DAGExecutor",
    "DAGSchema",
    "DagronError",
    "DataFramePipeline",
    "DataFrameSchema",
    "DuplicateNodeError",
    "EdgeNotFoundError",
    "ExecutionCallbacks",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStep",
    "ExecutionTrace",
    "GraphDiff",
    "GraphError",
    "GraphStats",
    "IncrementalExecutor",
    "IncrementalResult",
    "LintReport",
    "LintSeverity",
    "LintWarning",
    "Mutation",
    "MutationType",
    "NodeExplanation",
    "NodeId",
    "NodeIterator",
    "NodeLevelIterator",
    "NodeNotFoundError",
    "NodeProfile",
    "NodeResult",
    "NodeStatus",
    "Pipeline",
    "ProfileReport",
    "ReachabilityIndex",
    "ReactiveDAG",
    "ScheduledNode",
    "SchemaViolation",
    "TraceEvent",
    "TraceEventType",
    "VersionedDAG",
    "WhatIfResult",
    "compose",
    "from_records",
    "pretty_print",
    "profile_execution",
    "task",
    "validate_schema",
]
