"""dagron — A fast Rust-backed DAG engine for Python."""

from dagron._internal import (
    DAG,
    CycleError,
    DagronError,
    DuplicateNodeError,
    EdgeNotFoundError,
    ExecutionPlan,
    ExecutionStep,
    GraphDiff,
    GraphError,
    GraphStats,
    NodeId,
    NodeIterator,
    NodeLevelIterator,
    NodeNotFoundError,
    ReachabilityIndex,
    ScheduledNode,
)
from dagron._patches import apply_patches as _apply_patches
from dagron.analysis import (
    DAGSchema,
    LintReport,
    LintSeverity,
    LintWarning,
    NodeExplanation,
    WhatIfResult,
)
from dagron.builder import DAGBuilder
from dagron.compose import compose
from dagron.dataframe import (
    ColumnSchema,
    DataFramePipeline,
    DataFrameSchema,
    SchemaViolation,
    validate_schema,
)
from dagron.display import pretty_print
from dagron.execution import (
    ApprovalGate,
    AsyncDAGExecutor,
    AsyncResourceAwareExecutor,
    CachedDAGExecutor,
    CachedExecutionResult,
    CachePolicy,
    CacheStats,
    CheckpointExecutor,
    CheckpointInfo,
    ConditionalDAGBuilder,
    ConditionalExecutor,
    ContentAddressableCache,
    DAGExecutor,
    DynamicExecutor,
    DynamicModification,
    DynamicNodeSpec,
    ExecutionCallbacks,
    ExecutionResult,
    ExecutionTrace,
    GateController,
    GateRejectedError,
    GateStatus,
    GateTimeoutError,
    IncrementalExecutor,
    IncrementalResult,
    NodeProfile,
    NodeResult,
    NodeStatus,
    PartitionedDAGExecutor,
    Pipeline,
    ProfileReport,
    ReactiveDAG,
    ResourceAwareExecutor,
    ResourcePool,
    ResourceRequirements,
    ResourceSnapshot,
    ResourceTimeline,
    TraceEvent,
    TraceEventType,
    profile_execution,
    task,
)
from dagron.integration import from_records
from dagron.plugins import (
    DagronPlugin,
    HookContext,
    HookEvent,
    HookRegistry,
    PluginManager,
)
from dagron.template import DAGTemplate, TemplateError, TemplateParam
from dagron.versioning import Mutation, MutationType, VersionedDAG

_apply_patches()
del _apply_patches

# Module-level plugin manager singleton
_plugin_manager = PluginManager()

__version__ = "0.1.0"

__all__ = [
    "DAG",
    "ApprovalGate",
    "AsyncDAGExecutor",
    "AsyncResourceAwareExecutor",
    "CachePolicy",
    "CacheStats",
    "CachedDAGExecutor",
    "CachedExecutionResult",
    "CheckpointExecutor",
    "CheckpointInfo",
    "ColumnSchema",
    "ConditionalDAGBuilder",
    "ConditionalExecutor",
    "ContentAddressableCache",
    "CycleError",
    "DAGBuilder",
    "DAGExecutor",
    "DAGSchema",
    "DAGTemplate",
    "DagronError",
    "DagronPlugin",
    "DataFramePipeline",
    "DataFrameSchema",
    "DuplicateNodeError",
    "DynamicExecutor",
    "DynamicModification",
    "DynamicNodeSpec",
    "EdgeNotFoundError",
    "ExecutionCallbacks",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionStep",
    "ExecutionTrace",
    "GateController",
    "GateRejectedError",
    "GateStatus",
    "GateTimeoutError",
    "GraphDiff",
    "GraphError",
    "GraphStats",
    "HookContext",
    "HookEvent",
    "HookRegistry",
    "IncrementalExecutor",
    "IncrementalResult",
    "LintReport",
    "LintSeverity",
    "LintWarning",
    "Mutation",
    "MutationType",
    "NodeExplanation",
    "NodeId",
    "NodeIterator",
    "NodeLevelIterator",
    "NodeNotFoundError",
    "NodeProfile",
    "NodeResult",
    "NodeStatus",
    "PartitionedDAGExecutor",
    "Pipeline",
    "PluginManager",
    "ProfileReport",
    "ReachabilityIndex",
    "ReactiveDAG",
    "ResourceAwareExecutor",
    "ResourcePool",
    "ResourceRequirements",
    "ResourceSnapshot",
    "ResourceTimeline",
    "ScheduledNode",
    "SchemaViolation",
    "TemplateError",
    "TemplateParam",
    "TraceEvent",
    "TraceEventType",
    "VersionedDAG",
    "WhatIfResult",
    "compose",
    "from_records",
    "pretty_print",
    "profile_execution",
    "task",
    "validate_schema",
]
