"""Type stubs for dagron._internal (Rust extension module)."""

from typing import Any, Iterator, Optional

class NodeId:
    """An immutable identifier for a node in the DAG."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class DAG:
    """A directed acyclic graph backed by Rust."""

    def __init__(self) -> None: ...

    # Construction
    def add_node(
        self,
        name: str,
        payload: Any = None,
        metadata: Any = None,
    ) -> NodeId: ...
    def add_nodes(
        self,
        nodes: list[str | tuple[str, Any] | tuple[str, Any, Any]],
    ) -> list[NodeId]: ...
    def add_edge(
        self,
        from_node: str,
        to_node: str,
        weight: Optional[float] = None,
        label: Optional[str] = None,
    ) -> None: ...
    def add_edges(
        self,
        edges: list[
            tuple[str, str]
            | tuple[str, str, float]
            | tuple[str, str, float, str]
        ],
    ) -> None: ...
    def remove_node(self, name: str) -> None: ...
    def remove_edge(self, from_node: str, to_node: str) -> None: ...

    # Introspection
    def has_node(self, name: str) -> bool: ...
    def has_edge(self, from_node: str, to_node: str) -> bool: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def get_payload(self, name: str) -> Any: ...
    def set_payload(self, name: str, payload: Any) -> None: ...
    def get_metadata(self, name: str) -> Any: ...
    def set_metadata(self, name: str, metadata: Any) -> None: ...
    def predecessors(self, name: str) -> list[NodeId]: ...
    def successors(self, name: str) -> list[NodeId]: ...
    def ancestors(self, name: str) -> list[NodeId]: ...
    def descendants(self, name: str) -> list[NodeId]: ...
    def in_degree(self, name: str) -> int: ...
    def out_degree(self, name: str) -> int: ...
    def roots(self) -> list[NodeId]: ...
    def leaves(self) -> list[NodeId]: ...
    def nodes(self) -> list[NodeId]: ...
    def node_names(self) -> list[str]: ...
    def edges(self) -> list[tuple[str, str]]: ...

    # Validation
    def validate(self) -> bool: ...

    # Topological sorting
    def topological_sort(self) -> list[NodeId]: ...
    def topological_sort_dfs(self) -> list[NodeId]: ...
    def topological_levels(self) -> list[list[NodeId]]: ...

    # Protocols
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

# Exceptions
class DagronError(Exception): ...
class CycleError(DagronError): ...
class NodeNotFoundError(DagronError): ...
class DuplicateNodeError(DagronError): ...
class EdgeNotFoundError(DagronError): ...
class GraphError(DagronError): ...
