"""Type stubs for dagron._internal (Rust extension module)."""

from collections.abc import Callable, Iterator
from typing import Any, Literal

from dagron.builder import DAGBuilder

class NodeId:
    """An immutable identifier for a node in the DAG."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

class ScheduledNode:
    """A node with scheduling information."""

    @property
    def node(self) -> NodeId: ...
    @property
    def start_time(self) -> float: ...
    @property
    def duration(self) -> float: ...
    def __repr__(self) -> str: ...

class ExecutionStep:
    """A step in an execution plan containing nodes to run in parallel."""

    @property
    def step_index(self) -> int: ...
    @property
    def nodes(self) -> list[ScheduledNode]: ...
    def __repr__(self) -> str: ...

class ExecutionPlan:
    """An execution plan for the DAG."""

    @property
    def steps(self) -> list[ExecutionStep]: ...
    @property
    def total_nodes(self) -> int: ...
    @property
    def max_parallelism(self) -> int: ...
    @property
    def estimated_makespan(self) -> float: ...
    @property
    def critical_path(self) -> list[NodeId] | None: ...
    def __repr__(self) -> str: ...

class ReachabilityIndex:
    """Precomputed reachability index for O(1) ancestor/descendant queries.

    Build once with ``DAG.build_reachability_index()``, then query with
    ``can_reach()``, ``reachable_from()``, and ``ancestors_of()``.

    Note: The index becomes stale if the DAG is mutated after building.
    """

    def can_reach(self, from_node: str, to_node: str) -> bool: ...
    def reachable_from(self, node: str) -> list[str]: ...
    def ancestors_of(self, node: str) -> list[str]: ...
    def node_count(self) -> int: ...

class GraphStats:
    """Comprehensive graph statistics."""

    @property
    def node_count(self) -> int: ...
    @property
    def edge_count(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def width(self) -> int: ...
    @property
    def density(self) -> float: ...
    @property
    def longest_path_length(self) -> int: ...
    @property
    def avg_in_degree(self) -> float: ...
    @property
    def avg_out_degree(self) -> float: ...
    @property
    def max_in_degree(self) -> int: ...
    @property
    def max_out_degree(self) -> int: ...
    @property
    def root_count(self) -> int: ...
    @property
    def leaf_count(self) -> int: ...
    @property
    def is_weakly_connected(self) -> bool: ...
    @property
    def component_count(self) -> int: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class GraphDiff:
    """Result of diffing two DAGs."""

    @property
    def added_nodes(self) -> list[str]: ...
    @property
    def removed_nodes(self) -> list[str]: ...
    @property
    def changed_nodes(self) -> list[str]: ...
    @property
    def added_edges(self) -> list[tuple[str, str]]: ...
    @property
    def removed_edges(self) -> list[tuple[str, str]]: ...
    @property
    def changed_edges(self) -> list[tuple[str, str]]: ...
    def __repr__(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...

class NodeIterator:
    """Lazy iterator over nodes."""

    def __iter__(self) -> NodeIterator: ...
    def __next__(self) -> NodeId: ...
    def __len__(self) -> int: ...
    def collect(self) -> list[NodeId]: ...
    def __repr__(self) -> str: ...

class NodeLevelIterator:
    """Lazy iterator over topological levels."""

    def __iter__(self) -> NodeLevelIterator: ...
    def __next__(self) -> list[NodeId]: ...
    def __len__(self) -> int: ...
    def collect(self) -> list[list[NodeId]]: ...
    def __repr__(self) -> str: ...

class DAG:
    """A directed acyclic graph backed by Rust."""

    def __init__(self) -> None: ...

    # --- Properties ---
    @property
    def generation(self) -> int: ...

    # --- Construction ---
    def add_node(
        self,
        name: str,
        payload: Any = None,
        metadata: Any = None,
    ) -> NodeId: ...
    def add_nodes(
        self,
        nodes: list[str | tuple[str, Any] | tuple[str, Any, Any]],
    ) -> list[NodeId]: ...
    def add_edge(
        self,
        from_node: str,
        to_node: str,
        weight: float | None = None,
        label: str | None = None,
    ) -> None: ...
    def add_edges(
        self,
        edges: list[
            tuple[str, str] | tuple[str, str, float] | tuple[str, str, float, str]
        ],
    ) -> None: ...
    def remove_node(self, name: str) -> None: ...
    def remove_edge(self, from_node: str, to_node: str) -> None: ...
    @staticmethod
    def builder() -> DAGBuilder: ...

    # --- Introspection ---
    def has_node(self, name: str) -> bool: ...
    def has_edge(self, from_node: str, to_node: str) -> bool: ...
    def node_count(self) -> int: ...
    def edge_count(self) -> int: ...
    def get_payload(self, name: str) -> Any: ...
    def set_payload(self, name: str, payload: Any) -> None: ...
    def get_metadata(self, name: str) -> Any: ...
    def set_metadata(self, name: str, metadata: Any) -> None: ...
    def predecessors(self, name: str) -> list[NodeId]: ...
    def successors(self, name: str) -> list[NodeId]: ...
    def ancestors(self, name: str) -> list[NodeId]: ...
    def descendants(self, name: str) -> list[NodeId]: ...
    def in_degree(self, name: str) -> int: ...
    def out_degree(self, name: str) -> int: ...
    def roots(self) -> list[NodeId]: ...
    def leaves(self) -> list[NodeId]: ...
    def nodes(self) -> list[NodeId]: ...
    def node_names(self) -> list[str]: ...
    def edges(self) -> list[tuple[str, str]]: ...
    def iter_nodes(self) -> NodeIterator: ...
    def iter_roots(self) -> NodeIterator: ...
    def iter_leaves(self) -> NodeIterator: ...
    def iter_ancestors(self, name: str) -> NodeIterator: ...
    def iter_descendants(self, name: str) -> NodeIterator: ...

    # --- Validation ---
    def validate(self) -> bool: ...

    # --- Topological sorting ---
    def topological_sort(self) -> list[NodeId]: ...
    def topological_sort_dfs(self) -> list[NodeId]: ...
    def topological_levels(self) -> list[list[NodeId]]: ...
    def all_topological_orderings(
        self, limit: int | None = None
    ) -> list[list[NodeId]]: ...
    def iter_topological_sort(self) -> NodeIterator: ...
    def iter_topological_levels(self) -> NodeLevelIterator: ...

    # --- Priority sorting ---
    def topological_sort_priority(
        self, priorities: dict[str, float] | None = None
    ) -> list[NodeId]: ...
    def topological_levels_priority(
        self, priorities: dict[str, float] | None = None
    ) -> list[list[NodeId]]: ...

    # --- Scheduling ---
    def execution_plan(
        self, costs: dict[str, float] | None = None
    ) -> ExecutionPlan: ...
    def execution_plan_constrained(
        self,
        max_workers: int,
        costs: dict[str, float] | None = None,
    ) -> ExecutionPlan: ...
    def critical_path(
        self, costs: dict[str, float] | None = None
    ) -> tuple[list[NodeId], float]: ...

    # --- Serialization ---
    def to_json(
        self, payload_serializer: Callable[[Any], Any] | None = None
    ) -> str: ...
    @classmethod
    def from_json(
        cls,
        json_str: str,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...
    def to_dot(
        self,
        node_attrs: Callable[[str, Any], str | None] | None = None,
    ) -> str: ...
    def to_mermaid(self) -> str: ...
    def to_bytes(
        self, payload_serializer: Callable[[Any], Any] | None = None
    ) -> bytes: ...
    @classmethod
    def from_bytes(
        cls,
        data: bytes,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

    # --- Transforms ---
    def reverse(self) -> DAG: ...
    def collapse(
        self,
        nodes: list[str],
        collapsed_name: str,
        payload: Any = None,
    ) -> DAG: ...
    def dominator_tree(self, root: str) -> list[tuple[str, str]]: ...
    def snapshot(self) -> DAG: ...
    def transitive_reduction(self) -> DAG: ...
    def transitive_closure(self) -> DAG: ...
    def filter(self, predicate: Callable[[str, Any], bool]) -> DAG: ...
    def merge(
        self,
        other: DAG,
        conflict: Literal["keep_first", "keep_second", "error"] = "keep_first",
        conflict_resolver: Callable[[str, Any, Any], Any] | None = None,
    ) -> DAG: ...

    # --- Incremental ---
    def dirty_set(self, changed: list[str]) -> list[str]: ...
    def change_provenance(self, changed: list[str]) -> dict[str, list[str]]: ...

    # --- Subgraph ---
    def subgraph(self, nodes: list[str]) -> DAG: ...
    def subgraph_by_depth(
        self,
        root: str,
        depth: int,
        direction: Literal["forward", "backward", "both"] = "both",
    ) -> DAG: ...

    # --- Paths ---
    def all_paths(
        self,
        from_node: str,
        to_node: str,
        limit: int | None = None,
    ) -> list[list[NodeId]]: ...
    def shortest_path(self, from_node: str, to_node: str) -> list[NodeId] | None: ...
    def longest_path(
        self,
        from_node: str,
        to_node: str,
        costs: dict[str, float] | None = None,
    ) -> tuple[list[NodeId], float] | None: ...

    # --- Reachability ---
    def build_reachability_index(self) -> ReachabilityIndex: ...
    def is_ancestor(self, ancestor: str, descendant: str) -> bool: ...

    # --- Matching ---
    def nodes_matching_regex(self, pattern: str) -> list[NodeId]: ...
    def nodes_matching_glob(self, pattern: str) -> list[NodeId]: ...

    # --- Statistics ---
    def stats(self) -> GraphStats: ...

    # --- Diff ---
    def diff(self, other: DAG) -> GraphDiff: ...

    # --- Serialization (file) ---
    def save(
        self,
        path: str,
        payload_serializer: Callable[[Any], Any] | None = None,
    ) -> None: ...
    @classmethod
    def load(
        cls,
        path: str,
        payload_deserializer: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

    # --- Cache ---
    def cache_info(self) -> dict[str, int]: ...
    def clear_cache(self) -> None: ...

    # --- Protocols ---
    def __len__(self) -> int: ...
    def __contains__(self, name: str) -> bool: ...
    def __getitem__(self, name: str) -> Any: ...
    def __setitem__(self, name: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __repr__(self) -> str: ...
    def __bool__(self) -> bool: ...

    # --- Display (monkey-patched) ---
    def pretty_print(
        self,
        *,
        layout: Literal["vertical", "horizontal"] = "vertical",
        max_nodes: int = 50,
        show_payloads: bool = False,
        node_formatter: Callable[[str, Any], str] | None = None,
    ) -> str: ...
    def _repr_svg_(self) -> str: ...

    # --- Integration (monkey-patched) ---
    @staticmethod
    def from_records(
        records: Any,
        *,
        name_field: str = "name",
        edge_fn: Callable[[Any], list[str]] | None = None,
        payload_fn: Callable[[Any], Any] | None = None,
    ) -> DAG: ...

# Exceptions
class DagronError(Exception): ...
class CycleError(DagronError): ...
class NodeNotFoundError(DagronError): ...
class DuplicateNodeError(DagronError): ...
class EdgeNotFoundError(DagronError): ...
class GraphError(DagronError): ...
